baseURL = "https://hlth-460-uc.netlify.com/"
languageCode = "en-us"
title = "Course Notes" 
theme = "xmin"
[[menu.main]]
    name = "Home"
    url = "https://hlth-460-uc.netlify.com/"
    weight = 1
 
